# This is a basic workflow to help you get started with Actions

name: Vuepress

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
      - '.github/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Building Vuepress project
    - name: Deploy to Vuepress
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: cd docs && yarn install && yarn docs:build
        BUILD_DIR: sources/.vuepress/dist # as we cd'd to ./docs build dir is relative to that path